name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 4 * * *'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Update Code
        run: |
          git config --local user.email "el3954789@gmail.com"
          git config --local user.name "el3954789"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "try update"
          git push
